//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class academic
    {
        public int subject_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> subject { get; set; }
        public Nullable<int> exam { get; set; }
        public string results { get; set; }
        public string pass { get; set; }
    
        public virtual student student { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
